### ISSUE TITLE
[python 3] Gradual transition

### ISSUE THREAD

**Issue by woutdenolf** [tinaw/pyFDMNES#2]
This needs to be done at some point:
1. Add more unit tests first (especially for cif parsing).
2. Add continuous integration (Travis).
3. Use future/futurize to have code working in python 2/3.
4. Drop python 2 support.

Is this still the main repository?

**Comment by carichte** [comment]
Hi Wout,

thanks for the efforts. Recently I'm not so much active in spectroscopy anymore. I would be surprised if this wrapper still works with the latest FDMNES version.

If it's useful for you, I would be glad if you continue the development..
I can add you to the repo or you make your fork -- as you like.

**Comment by carichte** [comment]
.cif parsing should probably be outsourced to a third party package?

**Comment by woutdenolf** [comment]
As for the CIF parser, it seems hard to find a decently managed project for python. This may be a good candidate: https://github.com/glenveegee/PDBeCIF. Pure python with test suite but no pypi deployment or python 3 support. Or maybe it is better to use a more complete crystallographic toolbox (could also handle the spacegroup related stuff). I would avoid cctbx because of its unusual installation and runtime environment.

As for the central repo: I won't be spending much time on this so keep this as the central repo. If you don't want to review&merge pull requests you can add me as a collaborator.

As for supporting the latest FDMNES: seems to work, why wouldn't it? Are there brittle parts that you think can be broken easily?

**Comment by carichte** [comment]
Works with python3 now. Cif file loading via `PyCifRW` package
